# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1d31020718c92cc03d5631b069e0bee9"
name = "Announcement Pro"
application_url = "https://announcement-bar-pro.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "https://announcement-bar-pro.vercel.app/webhooks/app/compliance"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"



[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_themes"

[auth]
redirect_urls = [ "https://announcement-bar-pro.vercel.app/auth/callback" ]
